[manifest]
version = "1.0"
dump_lua = false
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''['en-us'] = {font = 1, label = "English", key = 'en-us', button = "Language Feedback", warning = {'This language is still in Beta. To help us','improve it, please click on the feedback button.', 'Click again to confirm'}},'''
position = "at"
payload = '''['en-us'] = {font = 1, label = "English", key = 'en-us', button = "Language Feedback", warning = {'This language is still in Beta. To help us','improve it, please click on the feedback button.', 'Click again to confirm'}},
['uk_UA'] = {font = 6, label = "Українська", key = 'uk_UA', beta = true, button = "Відгук", warning = {'Це мова встановлена за допомогою моду', "Натисніть знову щоб підтвердити"}},'''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''['ru'] = {font = 6, label = "Русский", key = 'ru', beta = true, button = "Отзыв о языке", warning = {'Этот язык все еще находится в Бета-версии. Чтобы помочь','нам его улучшить, пожалуйста, нажмите на кнопку обратной связи.', "Щелкните снова, чтобы подтвердить"}},'''
position = "at"
payload = ''''''
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.12, squish = 1, DESCSCALE = 1},'''
position = "at"
payload = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.12, squish = 0.7, DESCSCALE = 1},'''
overwrite = true
match_indent = true

# "Рахунок раунду" замість "Раунд рахунок"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_round'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "Рахунок", scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text =localize('k_lower_score'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "раунду", scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true


# "Огляд колоди" замість "Огляд колода"
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_deck'), scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "колоди", scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true

# Шриифт для знака гривні
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}}, maxw = 1.35, colours = {G.C.MONEY}, font = G.LANGUAGES['en-us'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}}, maxw = 1.35, colours = {G.C.MONEY}, font = G.LANGUAGES['uk_UA'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}'''
overwrite = true
match_indent = true